/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class moa_classifiers_evolutionary_DERules */

#ifndef _Included_moa_classifiers_evolutionary_DERules
#define _Included_moa_classifiers_evolutionary_DERules
#ifdef __cplusplus
extern "C" {
#endif
#undef moa_classifiers_evolutionary_DERules_serialVersionUID
#define moa_classifiers_evolutionary_DERules_serialVersionUID 1LL
#undef moa_classifiers_evolutionary_DERules_serialVersionUID
#define moa_classifiers_evolutionary_DERules_serialVersionUID 1LL
/*
 * Class:     moa_classifiers_evolutionary_DERules
 * Method:    contextualize
 * Signature: (IIIIIII)V
 */
JNIEXPORT void JNICALL Java_moa_classifiers_evolutionary_DERules_contextualize
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     moa_classifiers_evolutionary_DERules
 * Method:    copyDataset
 * Signature: (Lmoa/classifiers/evolutionary/DERules;I)V
 */
JNIEXPORT void JNICALL Java_moa_classifiers_evolutionary_DERules_copyDataset
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     moa_classifiers_evolutionary_DERules
 * Method:    train
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_moa_classifiers_evolutionary_DERules_train
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
